	CREATE DATABASE CLIENTES

	--Exercício 1
	CREATE TABLE CLIENTE
		(
		ID INT NOT NULL,
		NOME VARCHAR(20) NOT NULL,
		TELEFONE VARCHAR(11),
		ENDERECO VARCHAR(MAX) NOT NULL
		)

	--Exercício 2
	INSERT INTO CLIENTE (ID, NOME, TELEFONE, ENDERECO) VALUES (1, 'Vinicius Silva', '987654', 'Rua Girassol')
	INSERT INTO CLIENTE (ID, NOME, TELEFONE, ENDERECO) VALUES (2, 'Maria Antonia', '123456', 'Rua Rosas')
	INSERT INTO CLIENTE (ID, NOME, TELEFONE, ENDERECO) VALUES (3, 'Marcus Vinicius', '654123', 'Rua Itajai')

	--Exercício 3
	SELECT * FROM CLIENTE

	--Exercício 4
	SELECT ID FROM CLIENTE

	--Exercício 5
	SELECT *
	FROM CLIENTE
	WHERE NOME LIKE '%u%';

	--Exercício 6
	UPDATE CLIENTE
	SET ENDERECO = 'Rua do Limão'
	WHERE NOME = 'Marcus Vinicius';

	--Exercícoi 7
	DELETE FROM CLIENTE
	WHERE ID = 2;
